export type BarcodeCallback = (barcode: string) => void;

/**
 * BarcodeAuditor class acts as a buffer and manager for barcode scanner inputs.
 * It detects rapid successive keystrokes separated by small intervals, typically
 * generated by hardware barcode scanners (or USB converters).
 */
export class BarcodeAuditor {
    private buffer: string = '';
    private lastKeyTime: number = 0;
    private readonly timeoutMs: number;
    private onBarcodeScanned: BarcodeCallback;

    constructor(onBarcodeScanned: BarcodeCallback, timeoutMs: number = 120) {
        this.onBarcodeScanned = onBarcodeScanned;
        this.timeoutMs = timeoutMs;
    }

    public handleKeyDown = (e: KeyboardEvent) => {
        // Ignore modifier keys
        if (e.ctrlKey || e.altKey || e.metaKey) {
            return;
        }

        const currentTime = Date.now();
        const timeDiff = currentTime - this.lastKeyTime;
        this.lastKeyTime = currentTime;

        // If the delay is too long (user is typing manually or slow USB converter lag beyond our threshold), reset the buffer.
        if (timeDiff > this.timeoutMs) {
            this.buffer = '';
        }

        if (e.key === 'Enter') {
            // A typical barcode has at least 3 characters.
            if (this.buffer.length >= 3) {
                const code = this.buffer;
                this.buffer = '';
                
                // CRITICAL: Stop the event from reaching the React inputs and triggering a double add.
                // This requires this event listener to be added in the 'capture' phase on the window.
                e.stopPropagation();
                e.preventDefault();

                // If the user was focused on an input, clear it because the scanner just rapidly typed into it.
                const target = e.target as HTMLElement;
                if (target && (target.tagName === 'INPUT' || target.tagName === 'TEXTAREA')) {
                    const input = target as HTMLInputElement;
                    input.value = '';
                }

                // Fire callback to the main app
                this.onBarcodeScanned(code);
            } else {
                this.buffer = '';
            }
        } else if (e.key.length === 1) {
            // Append single printable characters to the buffer
            this.buffer += e.key;
        }
    };
}
